# Generated by Django 4.2.1 on 2023-05-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='profile',
        ),
    ]
